### ISSUE TITLE
Air gap installation requires update (docker compose)

### ISSUE THREAD

**Issue by AlexBaranowski** [aboutcode-org/scancode.io#1579]
Current offline installation require update to config files and probably documentation. The following should be fixed:

### docker-compose-offline.yml

```yaml
  web:
    image: scancodeio_web
```

Exported image is named scancodeio-web

```yaml
  worker:
    image: scancodeio_worker
```
Exported image is named scancodeio-worker

Also the starting command should be unified:

The docker-compose.yml vs docker-compose-offline.yml

```
 worker:
    image: scancodeio_worker
    command: wait-for-it web:8000 -- ./manage.py rqworker --worker-class scancodeio.worker.ScanCodeIOWorker --queue-class scancodeio.worker.ScanCodeIOQueue --verbosity 2
```

```
  worker:
    build: .
    # Ensure that potential db migrations run first by waiting until "web" is up
    command: wait-for-it --strict --timeout=120 web:8000 -- sh -c "
        ./manage.py rqworker --worker-class scancodeio.worker.ScanCodeIOWorker
                             --queue-class scancodeio.worker.ScanCodeIOQueue
                             --verbosity 1"
```

Lastly the clamav configuration is not present (image and volumes)

```
  clamav:
    image: clamav/clamav
    volumes:
      - clamav_data:/var/lib/clamav
      - workspace:/var/scancodeio/workspace/
    restart: always
(...)
volumes:
  (...)
  clamav_data:
  (...)
```

With `vimdiff` the configurations should probably not match only on `image: XXX` and `build: .`

### Makefile

Makefile should be updated so the `docker-images:` target would also export the clamav image.

### Documentation

Lastly documentation should be revisited to check if it's up to date.

Best,
Alex
