### ISSUE TITLE
Show where snippets were matched from

### ISSUE THREAD

**Issue by JonoYang** [aboutcode-org/scancode.io#1688]
When we display snippet matches in the codebaseresource viewer, we highlight the lines that were matched, but do not show which files from the matched package the snippet is from. We have the information in the match results returned, so the view should be updated to display that:

```
package: pkg:github/nodejs/string_decoder@v1.1.1
    resource: string_decoder-1.1.1/test/common/countdown.js
    similarity: '0.008403361344537815'
    match_detections:
```
