### ISSUE TITLE
Add LAYERS sheet to XLSX output for Docker scans uploaded to SCIO

### ISSUE THREAD

**Issue by mjherzog** [aboutcode-org/scancode.io#926]
It would be nice to get the LAYERS sheet in the XLSX output for a Docker scan added to the SCIO database with a load_inventory pipeline.

**Comment by tdruez** [comment]
@mjherzog Could you clarify what would you like to be imported from the LAYERS sheet? I'm not sure to get what's missing from the load_inventory pipeline import.

**Comment by mjherzog** [comment]
I am looking for the same LAYERS data that we get in the XLSX output when you run a Docker image scan directly in SCIO with a docker pipeline instead of loading an SCIO Docker scan (json) run on a different SCIO instance.
The fields are: 
- layer_tag
- created_by (Docker command)
- layer_id
- image_id
- created (date)
- size
- author
- comment
- xlsx_errors

The most important data are: created_by and the xref of layer_id to image_id.

**Comment by tdruez** [comment]
The LAYERS sheet is generated from the `Project.extra_data` field.

In the case of a JSON export, the integrality of that field is stored in the JSON and can be restored on load_inventory, but in the case of XLSX, most of the value is lost as we only keep the `layers` entries from the `Project.extra_data`.

We could convert back the `layers` data into the `Project.extra_data` field but the original data and structure will be lost and this may be problematic for the next export to XLSX.


---- 

Example of `Project.extra_data`

```
images:
  - os: linux
    tags:
      - alpine-mini:latest
    author:
    distro:
      os: linux
      logo:
      name: Alpine Linux
      id_like: []
      variant:
      version:
      build_id:
      cpe_name:
      home_url: https://alpinelinux.org/
      extra_data: {}
      identifier: alpine
      variant_id:
      version_id: 3.16.1
      pretty_name: Alpine Linux v3.16
      support_url:
      architecture: amd64
      bug_report_url: https://gitlab.alpinelinux.org/alpine/aports/-/issues
      version_codename:
      documentation_url:
      privacy_policy_url:
    labels: {}
    layers:
      - os:
        size: 305152
        author:
        labels: []
        sha256: 8826df928cad11bdd3830d029971f952660954d6afa8d3413093a77602d420e8
        comment: buildkit.dockerfile.v0
        created: '2022-08-02T00:49:43.155600296+02:00'
        variant:
        layer_id: 8826df928cad11bdd3830d029971f952660954d6afa8d3413093a77602d420e8
        created_by: 'ADD alpine.tar / # buildkit'
        os_version:
        architecture:
        docker_version:
        is_empty_layer: no
        archive_location: bbab8f037289d59a7464ec66c1b710097fe9bffe8e70467f4f6d8f54b8422aca/layer.tar
        extracted_location: docker-mini-with-license-alpine.tar.xz-extract/8826df928cad11bdd3830d029971f952660954d6afa8d3413093a77602d420e8
    sha256:
    comment:
    created: '2022-08-02T00:49:43.155600296+02:00'
    history:
      - comment: buildkit.dockerfile.v0
        created: '2022-08-02T00:49:43.155600296+02:00'
        created_by: 'ADD alpine.tar / # buildkit'
    variant:
    image_id: 33ebbbd3ccb4c86576d32eb638fbcaec9f600e715fbf918d1a6e7e7f00f95742
    os_version:
    architecture: amd64
    image_format: docker
    config_digest: sha256:33ebbbd3ccb4c86576d32eb638fbcaec9f600e715fbf918d1a6e7e7f00f95742
    docker_version:
```

Exported XLSX:
![Screenshot 2023-09-14 at 22 31 00](https://github.com/nexB/scancode.io/assets/489057/25c241be-ac08-4aa2-9cb6-89714d85c99b)
